import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Soft Toy Workshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navbar/>
        </header>
        <main className="h-fit overflow-hidden lg:mt-36 mt-24">
          {children}
        </main>
        {/* <Footer/> */}
      </body>
    </html>
  );
}
